export const RECEIVE_COUNTS = 'RECEIVE_COUNTS';
export const RECEIVE_ERROR = 'RECEIVE_ERROR';
export const REQUEST_DATA = 'REQUEST_DATA';

export const UPDATE_SORT = 'UPDATE_SORT';
export const UPDATE_ORDER = 'UPDATE_ORDER';
