export const REQUEST_DATA = 'REQUEST_DATA';
export const RECEIVE_COUNTS = 'RECEIVE_COUNTS';
export const RECEIVE_ERROR = 'RECEIVE_ERROR';
export const UPDATE_SORT = 'UPDATE_SORT';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const UPDATE_FETCHED_ORDERS = 'UPDATE_FETCHED_ORDERS';
export const CHECK_FETCHED_ORDERS = 'CHECK_FETCHED_ORDERS';
